project_name: girus-cli
version: 2

# Prevents parallel builds from stepping on each others toes downloading modules
before:
  hooks:
    - go mod tidy
    - git --no-pager diff --exit-code go.mod go.sum

gomod:
  proxy: true

sboms:
  - artifacts: binary

builds:
  - id: girus-cli
    binary: girus-cli-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    main: .
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/badtuxx/girus-cli/internal/common.Version={{ .Version }}
      - -X github.com/badtuxx/girus-cli/internal/common.BuildDate={{ .Date }}
      - -X github.com/badtuxx/girus-cli/internal/common.CommitID={{ .ShortCommit }}
      - -X github.com/badtuxx/girus-cli/internal/common.BuildUser={{ .Env.GITHUB_ACTOR }}
      - -X github.com/badtuxx/girus-cli/internal/common.GoOS={{ .Os }}
      - -X github.com/badtuxx/girus-cli/internal/common.GoArch={{ .Arch }}
      - -X github.com/badtuxx/girus-cli/internal/common.GoVersion={{ .Env.GOVERSION }}

signs:
  # Keyless
  - id: girus-cli
    signature: "${artifact}-keyless.sig"
    certificate: "${artifact}-keyless.pem"
    cmd: cosign
    args:
      [
        "sign-blob",
        "--yes",
        "--output-signature",
        "${artifact}.sig",
        "--output-certificate",
        "${artifact}.pem",
        "${artifact}",
      ]
    artifacts: binary
  - id: checksum
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args:
      [
        "sign-blob",
        "--yes",
        "--output-signature",
        "${artifact}-keyless.sig",
        "--output-certificate",
        "${artifact}.pem",
        "${artifact}",
      ]
    artifacts: checksum

archives:
  - formats:
      - binary
    name_template: "{{ .Binary }}"
    allow_different_binary_count: true

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  version_template: SNAPSHOT-{{ .ShortCommit }}

changelog:
  use: github-native
