apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-compose-lab-es
  namespace: girus
  labels:
    app: girus-lab-template
data:
  lab.yaml: |
    name: docker-compose-es
    title: "Introducción a Docker Compose"
    description: "Aprende a definir y ejecutar aplicaciones Docker multi-contenedor de forma declarativa con Docker Compose. Este laboratorio guiado explora los principios fundamentales de orquestación de contenedores para aplicaciones compuestas por múltiples servicios."
    duration: 25m
    image: "linuxtips/girus-devops:0.1"
    privileged: true # Acesso ao Docker daemon
    tasks:
      - name: "creando un archivo docker-compose.yaml"
        description: "Defina os servicios, redes e volumes da sua aplicación em un archivo YAML e entenda como o Docker Compose interpreta esta configuração para crear un ambiente multi-container."
        steps:
          - "**O Docker Compose** é uma ferramenta para definir e executar aplicações Docker multi-container. Ele utiliza un archivo YAML para configurar os servicios da aplicación e permite crear e iniciar todos os servicios com un único comando."
          - "Quando trabalhamos com aplicações reais, geralmente precisamos de vários containers que trabalham juntos (por ejemplo, un container para o frontend, outro para o backend e un terceiro para o banco de dados). O Docker Compose facilita essa orquestração."
          - "vamos comenzar creando un archivo chamado 'docker-compose.yaml' que define nuestra aplicación multi-container:"
          - |
            ```
            version: '3.8' # Especifica a versão da sintaxe do Compose

            services:
              webapp:
                image: nginx:alpine
                ports:
                  - "8080:80" # Mapeia puerta 8080 do host para 80 do container
                volumes:
                  - ./html:/usr/share/nginx/html:ro # Monta directorio local como read-only
                networks:
                  - app-net

              redis:
                image: redis:alpine
                networks:
                  - app-net

            networks:
              app-net: # Define uma rede customizada
                driver: bridge

            volumes: {} # Seção de volumes (vazia neste ejemplo)
            ```
          - "vamos entender os principais componentes deste archivo:"
          - "- **version**: Especifica a versão da sintaxe do Docker Compose que estamos usando. A versão '3.8' supuerta recursos mais recentes."
          - "- **services**: Define os containers que farão parte da aplicación. Cada servicio se tornará un container Docker."
          - "  - **webapp**: un servicio usando a imagen Nginx (servidor web) com a puerta 8080 do host mapeada para a puerta 80 do container."
          - "  - **redis**: un servicio usando a imagen Redis (banco de dados em memória)."
          - "- **networks**: Define as redes que os containers usarão para se comunicar."
          - "- **volumes**: Define os volumes que serão usados pelos containers para persistência de dados."
          - "Agora, precisamos crear o conteúdo que será servido pelo Nginx. vamos crear un directorio 'html' e un archivo 'index.html' dentro dele:"
          - "`mkdir html`"
          - "Este comando cria un directorio 'html' no directorio atual. Este directorio será montado dentro do container Nginx."
          - "`echo '<h1>Bem-vindo ao Docker Compose!</h1>' > html/index.html`"
          - "Este comando cria un archivo 'index.html' com un conteúdo HTML básico. O Nginx servirá este archivo quando acessarmos a aplicación."
          - "Antes de executarmos a aplicación, é uma boa prática verificar se o archivo docker-compose.yaml está sintaticamente correto:"
          - "`docker compose config`"
          - "Este comando valida o archivo docker-compose.yaml e exibe a configuração resultante. Se houver erros de sintaxe, eles serão exibidos aqui."
        tips:
          - type: "info"
            title: "Estrutura do Compose"
            content: "O archivo docker-compose.yaml define 'services' (containers), 'networks' (redes) e 'volumes'. Cada servicio tem opções como 'image', 'ports', 'volumes', 'environment', etc. A indentação no YAML é crítica - use espaços, não tabs."
          - type: "tip"
            title: "Versões do Compose"
            content: "Diferentes versões do Docker Compose supuertam diferentes recursos. A versão '3' e suas subversões são as mais recentes e recomendadas. Versões mais antigas (1.x, 2.x) têm sintaxe ligeiramente diferente. Atualmemte, a propriedade `version` não é mais necessária e tem função informativa. Ao usá-la usted receberá uma mensagem (warning) informando que o seu uso é obsoleto"
          - type: "warning"
            title: "Nomes de servicios"
            content: "Os nomes dos servicios definidos no docker-compose.yaml se tornam nomes DNS na rede do Docker. No nosso ejemplo, o servicio 'webapp' pode se comunicar com o Redis usando simplesmente o hostname 'redis'."
        validation:
          - command: "test -f docker-compose.yaml && test -f html/index.html && echo 'ok'"
            expectedOutput: "ok"
            errorMessage: "O archivo docker-compose.yaml ou html/index.html não foi criado corretamente. verifique se usted seguiu os passos para crear ambos os archivos."

      - name: "Executando a aplicación com Compose"
        description: "Use comandos do Docker Compose para iniciar, parar e administrar sua aplicación multi-container, entendendo o ciclo de vida dos containers e como eles se comunicam entre si."
        steps:
          - "Agora que temos nuestra configuração pronta, vamos iniciar nuestra aplicación multi-container usando o Docker Compose."
          - "O comando principal do Docker Compose é o <code>docker compose up</code>, que cria e inicia todos os containers definidos no archivo docker-compose.yaml."
          - "vamos iniciar nuestra aplicación em modo background (detached) para que possamos continuar usando o terminal:"
          - "`docker compose up -d`"
          - "A flag <code>-d</code> (detached) faz com que os containers rodem em background, liberando o terminal. Sem esta flag, veríamos os logs dos containers no terminal."
          - "O que acontece quando executamos este comando:"
          - "1. O Docker Compose lê o archivo docker-compose.yaml"
          - "2. Cria a rede 'app-net' definida no archivo (se não existir)"
          - "3. Puxa as imagens necessárias (nginx:alpine e redis:alpine) se não estiverem disponíveis localmente"
          - "4. Cria e inicia os containers para os servicios 'webapp' e 'redis'"
          - "5. Configura as puertas, volumes e redes conforme especificado"
          - "vamos verificar os containers criados pelo Docker Compose:"
          - "`docker compose ps`"
          - "Este comando lista todos os containers que fazem parte da aplicación definida no docker-compose.yaml do directorio atual. usted debe ver dois containers em execução ('webapp' e 'redis')."
          - "Para ver os logs gerados pelo servicio 'webapp' (Nginx):"
          - "`docker compose logs webapp`"
          - "O comando <code>logs</code> exibe os logs de un servicio específico. usted pode omitir o nome do servicio para ver logs de todos os servicios, ou adicionar <code>-f</code> para seguir os logs em tempo real (<code>docker compose logs -f</code>)."
          - "Agora, vamos acessar a aplicación web para confirmar que está funcionando:"
          - "`curl localhost:8080`"
          - "Este comando envia uma requisição HTTP para o servidor Nginx rodando na puerta 8080. usted debe ver o conteúdo do archivo 'index.html' que criamos."
          - "Poderíamos também acessar a aplicación através de un navegador, abrindo http://localhost:8080."
          - "Observe que o Compose configurou automaticamente a comunicação entre os containers. O servicio 'webapp' pode se comunicar com o 'redis' usando simplesmente o nome 'redis' como hostname, já que ambos estão na mesma rede 'app-net'."
        tips:
          - type: "tip"
            title: "comandos 'up' e 'down'"
            content: "`docker-compose up` cria e inicia os containers (e redes/volumes se não existirem). `docker-compose down` para e remove os containers e a rede padrão criada pelo compose. Adicionar `-d` ao comando 'up' faz com que os containers rodem em background."
          - type: "info"
            title: "Comunicação entre servicios"
            content: "Os servicios em un mesmo docker-compose podem se comunicar entre si usando o nome do servicio como hostname. Por ejemplo, em nosso 'webapp' poderíamos conectar ao Redis usando o hostname 'redis' e a puerta padrão 6379."
          - type: "tip"
            title: "Visualizando os Logs"
            content: "Além de `docker-compose logs [servicio]`, usted pode acompanhar os logs em tempo real com `docker-compose logs -f [servicio]`. Pressione Ctrl+C para sair do modo de acompanhamento."
        validation:
          - command: "curl -s localhost:8080 | grep 'Docker Compose'"
            expectedOutput: "<h1>Bem-vindo ao Docker Compose!</h1>"
            errorMessage: "Não foi possível acessar a aplicación Nginx via curl ou o conteúdo está incorreto. verifique se os containers estão em execução com 'docker-compose ps'."

      - name: "Parando e Removendo a aplicación"
        description: "aprende os diferentes comandos para administrar o ciclo de vida dos servicios no Docker Compose, entendendo a diferença entre parar containers, removê-los e limpar recursos."
        steps:
          - "Agora que entendemos como nuestra aplicación multi-container funciona, vamos aprender a administrar seu ciclo de vida de forma eficiente."
          - "Existem diferentes comandos no Docker Compose para parar e iniciar servicios, dependendo do que usted precisa:"
          - "vamos comenzar parando os servicios sem remover os containers:"
          - "`docker compose stop`"
          - "O comando <code>stop</code> envia un sinal SIGTERM para os containers, dando a eles tempo para se encerrar graciosamente. Os containers permanecem existindo, apenas são parados."
          - "vamos verificar o status dos containers após o comando stop:"
          - "`docker compose ps`"
          - "usted debe ver que os status dos containers agora é 'Exited' ou similar, indicando que eles não estão mais em execução, mas ainda existem."
          - "Agora, vamos iniciar os servicios novamente sem precisar recriá-los:"
          - "`docker compose start`"
          - "O comando <code>start</code> inicia containers existentes que foram parados anteriormente. É mais rápido que <code>up</code> porque não precisa recrear os containers."
          - "vamos verificar o status após o start:"
          - "`docker compose ps`"
          - "Os containers debem estar novamente no estado 'Up' ou 'Running'."
          - "Quando não precisamos mais da aplicación, podemos parar e remover completamente todos os recursos:"
          - "`docker compose down`"
          - "O comando <code>down</code> é mais completo que <code>stop</code>:"
          - "1. Para todos os containers (como o <code>stop</code>)"
          - "2. Remove os containers parados"
          - "3. Remove a rede criada pelo Compose"
          - "No entanto, ele não remove volumes nomeados por padrão."
          - "vamos verificar se os containers foram realmente removidos:"
          - "`docker compose ps`"
          - "usted não debe ver nenhun container listado, indicando que foram removidos com sucesso."
          - "Se nuestra aplicación tivesse volumes nomeados e quiséssemos removê-los também, usaríamos:"
          - "`docker compose down --volumes`"
          - "Este comando remove tudo que o <code>down</code> normal remove, mas também remove os volumes nomeados definidos no archivo docker-compose.yaml e os volumes anônimos associados aos containers."
          - "Finalmente, vamos remover os archivos que criamos para este laboratorio:"
          - "`rm -f docker-compose.yaml && rm -rf html`"
          - "Estes comandos removerão o archivo docker-compose.yaml e o directorio html com seu conteúdo."
        tips:
          - type: "warning"
            title: "`docker-compose down --volumes`"
            content: "O comando `down --volumes` remove containers, redes E volumes definidos na seção `volumes` do compose ou volumes anônimos criados pelos containers. Use com cuidado se precisar manter os dados persistentes."
          - type: "info"
            title: "Ciclo de Vida dos Containers"
            content: "O Docker Compose segue o mesmo ciclo de vida do Docker: 'create' (crear) -> 'start' (iniciar) -> 'stop' (parar) -> 'rm' (remover). O comando 'up' combina 'create' e 'start', enquanto 'down' combina 'stop' e 'rm'."
          - type: "tip"
            title: "Diferença entre Parar e Remover"
            content: "Ao parar un container com `stop`, seus dados e configurações são preservados, e ele pode ser reiniciado rapidamente com `start`. Remover un container com `down` elimina completamente o container, e recriá-lo exigirá mais recursos."
          - type: "info"
            title: "comandos Adicionais"
            content: "Outros comandos úteis incluem: `docker-compose restart` (reinicia containers sem recriação), `docker-compose pause`/`unpause` (pausa/despausa sem parar), `docker-compose exec` (executa comandos em containers em execução)."
        validation:
          - command: "docker container ls -q | wc -l" # debe retornar 0 containers
            expectedOutput: "0"
            errorMessage: "Os containers do Docker Compose não foram removidos corretamente com 'docker compose down'. verifique se executou o comando e se não há containers listados com 'docker compose ps'."
          - command: "test -f docker-compose.yaml || test -d html || echo 'cleaned'"
            expectedOutput: "cleaned"
            errorMessage: "Os archivos e directorios criados durante o laboratorio não foram removidos corretamente. Execute 'rm -f docker-compose.yaml && rm -rf html' para limpar." 
