apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-rds-elasticache-lab
  namespace: girus
  labels:
    app: girus-lab-template
data:
  lab.yaml: |
    name: aws-rds-elasticache
    title: "RDS e ElastiCache na AWS"
    description: "Aprenda a configurar e gerenciar bancos de dados gerenciados com RDS e caches com ElastiCache na AWS. Este laboratório guiado explora conceitos de banco de dados e cache em nuvem."
    duration: 45m
    image: "linuxtips/girus-devops:0.1"
    privileged: true
    tasks:
      - name: "Configurando RDS"
        description: "Aprenda a criar e configurar instâncias RDS."
        steps:
          - description: "Crie um grupo de subnets para RDS"
            command: "aws rds create-db-subnet-group --db-subnet-group-name lab-subnet-group --db-subnet-group-description 'Subnet group for RDS lab' --subnet-ids $(aws ec2 describe-subnets --filters 'Name=tag:Name,Values=PublicSubnet1' --query 'Subnets[0].SubnetId' --output text)"
            expectedOutput: "DBSubnetGroup"
            hint: "Use o comando aws rds create-db-subnet-group"

          - description: "Crie um grupo de segurança para RDS"
            command: "aws ec2 create-security-group --group-name RDSSecurityGroup --description 'Security group for RDS' --vpc-id $(aws ec2 describe-vpcs --filters 'Name=tag:Name,Values=LabVPC' --query 'Vpcs[0].VpcId' --output text)"
            expectedOutput: "GroupId"
            hint: "Use o comando aws ec2 create-security-group"

          - description: "Crie uma instância RDS"
            command: "aws rds create-db-instance --db-instance-identifier lab-db --db-instance-class db.t3.micro --engine mysql --master-username admin --master-user-password password123 --allocated-storage 20 --db-subnet-group-name lab-subnet-group --vpc-security-group-ids $(aws ec2 describe-security-groups --filters 'Name=group-name,Values=RDSSecurityGroup' --query 'SecurityGroups[0].GroupId' --output text)"
            expectedOutput: "DBInstance"
            hint: "Use o comando aws rds create-db-instance"

      - name: "Gerenciamento de RDS"
        description: "Aprenda a gerenciar e monitorar instâncias RDS."
        steps:
          - description: "Verifique o status da instância RDS"
            command: "aws rds describe-db-instances --db-instance-identifier lab-db --query 'DBInstances[0].DBInstanceStatus' --output text"
            expectedOutput: "available"
            hint: "Use o comando aws rds describe-db-instances"

          - description: "Crie um snapshot do banco de dados"
            command: "aws rds create-db-snapshot --db-snapshot-identifier lab-snapshot --db-instance-identifier lab-db"
            expectedOutput: "DBSnapshot"
            hint: "Use o comando aws rds create-db-snapshot"

          - description: "Configure backups automáticos"
            command: "aws rds modify-db-instance --db-instance-identifier lab-db --backup-retention-period 7 --preferred-backup-window '03:00-04:00'"
            expectedOutput: "DBInstance"
            hint: "Use o comando aws rds modify-db-instance"

      - name: "Configurando ElastiCache"
        description: "Aprenda a criar e configurar clusters ElastiCache."
        steps:
          - description: "Crie um grupo de subnets para ElastiCache"
            command: "aws elasticache create-cache-subnet-group --cache-subnet-group-name lab-cache-subnet --cache-subnet-group-description 'Subnet group for ElastiCache lab' --subnet-ids $(aws ec2 describe-subnets --filters 'Name=tag:Name,Values=PublicSubnet1' --query 'Subnets[0].SubnetId' --output text)"
            expectedOutput: "CacheSubnetGroup"
            hint: "Use o comando aws elasticache create-cache-subnet-group"

          - description: "Crie um grupo de segurança para ElastiCache"
            command: "aws ec2 create-security-group --group-name CacheSecurityGroup --description 'Security group for ElastiCache' --vpc-id $(aws ec2 describe-vpcs --filters 'Name=tag:Name,Values=LabVPC' --query 'Vpcs[0].VpcId' --output text)"
            expectedOutput: "GroupId"
            hint: "Use o comando aws ec2 create-security-group"

          - description: "Crie um cluster ElastiCache"
            command: "aws elasticache create-cache-cluster --cache-cluster-id lab-cache --engine redis --cache-node-type cache.t3.micro --num-cache-nodes 1 --cache-subnet-group-name lab-cache-subnet --security-group-ids $(aws ec2 describe-security-groups --filters 'Name=group-name,Values=CacheSecurityGroup' --query 'SecurityGroups[0].GroupId' --output text)"
            expectedOutput: "CacheCluster"
            hint: "Use o comando aws elasticache create-cache-cluster"
