apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-volumes-lab-es
  namespace: girus
  labels:
    app: girus-lab-template
data:
  lab.yaml: |
    name: docker-volumes-es
    title: "Persistência de Dados com Docker Volumes"
    description: "aprende a persistir dados de containers usando bind mounts e named volumes neste laboratorio detalhado e guiado. Entenda conceitos fundamentais para garantir que seus dados persistam além do ciclo de vida dos containers."
    duration: 20m
    image: "linuxtips/girus-devops:0.1"
    privileged: true # Acesso ao Docker daemon
    tasks:
      - name: "Usando Bind Mounts"
        description: "Mapeie un directorio do host para dentro de un container, entendendo como os dados podem ser compartilhados entre o sistema host e os containers Docker."
        steps:
          - "Os **bind mounts** são un dos mecanismos fundamentais de persistência de dados no Docker. Eles permitem mapear un directorio ou archivo do host diretamente para un container."
          - "vamos comenzar creando un directorio no host que será usado para demonstrar este conceito:"
          - "`mkdir dados_host`"
          - "Agora, vamos crear un archivo de texto simples dentro deste directorio para demonstrar a persistência:"
          - "`echo 'Dados do Host!' > dados_host/archivo_host.txt`"
          - "vamos verificar se o archivo foi criado corretamente:"
          - "`cat dados_host/archivo_host.txt`"
          - "Agora vamos executar un container Alpine e montar o directorio 'dados_host' em '/app/data' dentro do container:"
          - "`docker run --rm -v $(pwd)/dados_host:/app/data alpine ls /app/data`"
          - "Observe que usamos a flag `-v` para especificar o mapeamento entre o directorio do host e o directorio dentro do container."
          - "O formato desse mapeamento é `-v <caminho_no_host>:<caminho_no_container>`."
          - "vamos ler o conteúdo do archivo de dentro do container para confirmar que ele está acessível:"
          - "`docker run --rm -v $(pwd)/dados_host:/app/data alpine cat /app/data/archivo_host.txt`"
          - "Uma das vantagens dos bind mounts é que qualquer modificação no archivo, seja pelo host ou pelo container, é instantaneamente visível para ambos. vamos demonstrar isso modificando o archivo de dentro de un container:"
          - "`docker run --rm -v $(pwd)/dados_host:/app/data alpine sh -c 'echo \"Modificado pelo container\" > /app/data/archivo_host.txt'`"
          - "Agora, verifique o conteúdo do archivo no host para confirmar que a modificação feita pelo container foi persistida:"
          - "`cat dados_host/archivo_host.txt`"
          - "usted debe ver o texto 'Modificado pelo container', demonstrando que as alterações são bidirecionais."
          - "Para limpar nosso ambiente, remova o directorio criado:"
          - "`rm -rf dados_host`"
        tips:
          - type: "warning"
            title: "Bind Mounts e Permissões"
            content: "Bind mounts refletem diretamente o filesystem do host. Tenha cuidado com permissões e possíveis modificações indesejadas em archivos do host. Os containers operam com os mesmos privilégios do usuário que iniciou o Docker daemon, o que pode levar a problemas de segurança se não for gerenciado adequadamente."
          - type: "info"
            title: "Caminho Absoluto"
            content: "É recomendado usar caminhos absolutos para o directorio do host em bind mounts, como `$(pwd)/dados_host` que resolve para o caminho absoluto do directorio atual. Isso evita confusões sobre qual directorio está sendo montado."
          - type: "tip"
            title: "Modo somente leitura"
            content: "Se usted deseja permitir que o container apenas leia os dados, mas não os modifique, usted pode adicionar `:ro` ao final do mapeamento: `-v $(pwd)/dados_host:/app/data:ro`."
        validation:
          - command: "cat dados_host/archivo_host.txt 2>/dev/null || echo 'cleaned'" # Verifica se foi limpo
            expectedOutput: "cleaned"
            errorMessage: "O directorio 'dados_host' ou seu conteúdo não foi removido corretamente. Execute `rm -rf dados_host` para limpar o ambiente."

      - name: "Usando Named Volumes"
        description: "crea e administra volumes gerenciados pelo Docker para persistência de dados mais robusta e independente da estrutura de directorios do host."
        steps:
          - "Os **named volumes** são a forma preferida de persistir dados em containers Docker para aplicações em produção. Diferente dos bind mounts, os named volumes são completamente gerenciados pelo Docker e não dependem da estrutura de directorios do host."
          - "vamos crear un volume nomeado gerenciado pelo Docker:"
          - "`docker volume create meu_volume`"
          - "Esta operação cria un volume que será gerenciado pelo Docker. Os dados deste volume serão armazenados em un local específico gerenciado pelo Docker, geralmente em `/var/lib/docker/volumes/`."
          - "vamos listar os volumes Docker para confirmar que nosso volume foi criado:"
          - "`docker volume ls`"
          - "Para obter informações detalhadas sobre o volume, podemos inspecioná-lo:"
          - "`docker volume inspect meu_volume`"
          - "usted verá detalhes como o driver usado, o ponto de montagem no host e quaisquer opções de montagem."
          - "Agora, vamos executar un container e escrever dados no volume montado em '/data':"
          - "`docker run --rm -v meu_volume:/data alpine sh -c 'echo \"Dados persistidos no volume\" > /data/dados.txt'`"
          - "Observe que ao usar named volumes, usted não precisa especificar un caminho completo para o host, apenas o nome do volume."
          - "Mesmo após o container ser removido (devido à flag `--rm`), os dados permanecem no volume. vamos verificar isso executando outro container e lendo os dados do mesmo volume:"
          - "`docker run --rm -v meu_volume:/data alpine cat /data/dados.txt`"
          - "usted deberá ver 'Dados persistidos no volume', confirmando que os dados sobreviveram ao ciclo de vida do container."
          - "Podemos até crear un novo archivo ou modificar o existente e ele continuará persistindo:"
          - "`docker run --rm -v meu_volume:/data alpine sh -c 'echo \"Linha adicional\" >> /data/dados.txt'`"
          - "vamos verificar as modificações:"
          - "`docker run --rm -v meu_volume:/data alpine cat /data/dados.txt`"
        tips:
          - type: "tip"
            title: "Vantagens dos Named Volumes"
            content: "Named volumes são gerenciados pelo Docker, independentes do filesystem do host, mais portáveis e geralmente a forma preferida de persistir dados de containers. Eles são mais fáceis de fazer backup, migrar entre hosts e são mais compatíveis com orquestradores como o Docker Swarm e Kubernetes."
          - type: "info"
            title: "Volumes vs Bind Mounts"
            content: "Use named volumes quando o foco for a persistência de dados do container, especialmente para bancos de dados e aplicações que geram dados. Use bind mounts quando precisar compartilhar archivos específicos entre o host e o container, como código-fonte durante o desenvolvimento."
          - type: "warning"
            title: "Localização dos dados"
            content: "Embora usted possa inspecionar onde os dados do volume estão fisicamente armazenados no host com `docker volume inspect`, é considerada uma má prática acessar diretamente esses archivos. Sempre use o Docker para interagir com os volumes."
        validation:
          - command: "docker run --rm -v meu_volume:/data alpine cat /data/dados.txt | grep 'Dados persistidos no volume'"
            expectedOutput: "Dados persistidos no volume"
            errorMessage: "Não foi possível ler os dados escritos no named volume 'meu_volume'. verifique se o volume foi criado corretamente e se os dados foram escritos."

      - name: "Gerenciando Named Volumes"
        description: "aprende a listar, inspecionar e remover volumes Docker, entendendo o ciclo de vida dos dados persistidos e as melhores práticas para administración."
        steps:
          - "O administración adequado de volumes é crucial para evitar acúmulo de dados não utilizados e garantir a segurança dos dados impuertontes."
          - "Primeiro, vamos verificar se o nosso 'meu_volume' ainda existe:"
          - "`docker volume ls | grep meu_volume`"
          - "Os volumes Docker persistem mesmo após os containers que os utilizam serem removidos. Isso é ótimo para persistência, mas também significa que usted precisa administrar manualmente a limpeza."
          - "Para remover un volume específico, usamos o comando 'docker volume rm':"
          - "`docker volume rm meu_volume`"
          - "vamos verificar se o volume foi removido corretamente:"
          - "`docker volume ls | grep meu_volume || echo 'Volume removido'`"
          - "Se não houver saída da primeira parte do comando (docker volume ls | grep), o texto 'Volume removido' será exibido, confirmando a remoção."
          - "O Docker impede a remoção de volumes que estão sendo utilizados por containers (mesmo parados). Tente remover un volume que não existe (debe dar erro):"
          - "`docker volume rm volume_inexistente || echo 'Erro esperado'`"
          - "Em sistemas de produção, é comun acumular volumes não utilizados após remover containers. Para limpar todos os volumes 'dangling' (não associados a nenhun container), use:"
          - "`docker volume prune -f`" # -f para não pedir confirmação
          - "A flag '-f' pula a confirmação, mas em ambientes de produção, usted pode querer remover a flag para revisar o que será removido."
          - "vamos crear alguns volumes temporários para demonstrar o prune:"
          - "`docker volume create temp_volume1`"
          - "`docker volume create temp_volume2`"
          - "Agora executamos o prune novamente para remover esses volumes não utilizados:"
          - "`docker volume prune -f`"
          - "Verificamos que todos os volumes temporários foram removidos:"
          - "`docker volume ls | grep temp_ || echo 'Volumes temporários removidos'`"
        tips:
          - type: "warning"
            title: "Remoção de Volumes"
            content: "Remover un volume apaga permanentemente todos os dados armazenados nele. Tenha certeza antes de executar `docker volume rm` ou `docker volume prune`. Em ambientes de produção, considere implementar políticas de backup antes de remover volumes."
          - type: "info"
            title: "Volume Dangling"
            content: "un volume 'dangling' é aquele que não está mais associado a nenhun container. O comando `docker volume ls -f dangling=true` lista apenas esses volumes, útil para verificar quais volumes podem ser removidos com segurança."
          - type: "tip"
            title: "Nomeando Volumes"
            content: "Adote uma convenção de nomenclatura clara para seus volumes, como 'app_database', 'app_logs', etc. Isso facilita identificar o propósito de cada volume e gerenciá-los de forma mais eficiente."
        validation:
          - command: "docker volume ls | grep meu_volume || echo 'Volume removido'"
            expectedOutput: "Volume removido"
            errorMessage: "O volume 'meu_volume' não foi removido corretamente. Execute 'docker volume rm meu_volume' para remover." 
          - command: "docker volume ls | grep temp_ || echo 'Volumes temporários removidos'"
            expectedOutput: "Volumes temporários removidos"
            errorMessage: "Os volumes temporários não foram removidos corretamente. Execute 'docker volume prune -f' para limpar."
